### PR TITLE
Update README highlighting the features of the app

### PR DESCRIPTION
**Pull request by denisvieira05**
# Pull Request

## What I did

Add informations of the app on Readme, issue https://github.com/NIT-Meghalaya/Shishir-2019-App/issues/156

## How to verify it

See the file

### CODE REVIEW

**Comment by denisvieira05** [comment]
@Devansh-Maurya you can verify this PR ?

**Review by Devansh-Maurya — CHANGES_REQUESTED** [review]
Thanks for the PR @denisvieira05 . Please add the names of the other two developers too in the readme's **Developers** section

**Comment by denisvieira05** [comment]
> Thanks for the PR @denisvieira05 . Please add the names of the other two developers too in the readme's **Developers** section

of course @Devansh-Maurya , what's usernames I should be add ?

**Comment by Devansh-Maurya** [comment]
Please add the names from [here](https://github.com/NIT-Meghalaya/Shishir-2019-App/graphs/contributors), except the bot of course.

**Comment by denisvieira05** [comment]
Done @Devansh-Maurya !!

**Review by Devansh-Maurya — APPROVED** [review]
Thanks for the contribution @denisvieira05. Looks good to me now 👍

**Pull request merged**
